steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'VEXUS'
    args: ['build', '-t', 'gcr.io/plucky-weaver-450819-k7/vexus-ai', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/plucky-weaver-450819-k7/vexus-ai']

images:
  - 'gcr.io/plucky-weaver-450819-k7/vexus-ai'

timeout: '1800s'
